allowBuilds:
  esbuild: true
  workerd: true
  sharp: true
minimumReleaseAgeExclude:
  - '@sveltejs/kit@3.0.0-next.29'
  - '@vitest/mocker@5.0.2'
  - '@vitest/spy@5.0.2'
  - miniflare@5.20260923.0-alpha
  - vitest@5.0.2
  - wrangler@4.140.0
